<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>LocalEcho</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="8.0.8" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LocalEcho.Application\LocalEcho.Application.csproj" />
        <ProjectReference Include="..\LocalEcho.Infrastructure\LocalEcho.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\avatars\3707a93a-7e21-431d-9d8d-9db027c4161c.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\44054b95-8ba0-4427-b048-6c17a9eeff13.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\8fbae2a6-9b76-46e7-85c4-962aae589b69.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\ava1.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\ava2.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\ava3.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\avatar.png" />
      <_ContentIncludedByDefault Remove="wwwroot\avatars\avatar2.png" />
    </ItemGroup>

</Project>
